export const reservedModelParameterKeys = [
  'apiKey',
  'api_key',
  'baseURL',
  'baseUrl',
  'base_url',
  'modelListUrl',
  'model_list_url',
  'modelListAuth',
  'model_list_auth',
  'capabilities',
  'contextCompressionEnabled',
  'contextCompressionThreshold',
  'context_compression_enabled',
  'context_compression_threshold',
  'conversation',
  'defaultParameterPresetId',
  'default_parameter_preset_id',
  'displayName',
  'display_name',
  'function_call',
  'functions',
  'id',
  'input',
  'maxContextTokens',
  'maxCompletionTokens',
  'maxOutputTokens',
  'maxRetries',
  'maxTokens',
  'max_completion_tokens',
  'max_context_tokens',
  'max_output_tokens',
  'max_retries',
  'max_tokens',
  'messages',
  'model',
  'name',
  'parameters',
  'parameterPresetMode',
  'parameterPresets',
  'parameter_preset_mode',
  'parameter_presets',
  'previous_response_id',
  'prompt',
  'protocol',
  'provider',
  'stream',
  'streaming',
  'system',
  'toolUse',
  'tool_use',
  'vision'
] as const

const reservedModelParameterKeySet = new Set<string>(reservedModelParameterKeys)

export function modelReservedParameterKeys(parameters: Record<string, unknown>): string[] {
  return Object.keys(parameters).filter((key) => reservedModelParameterKeySet.has(key)).sort()
}
